# Generated by Django 5.1.2 on 2024-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True)),
                ('anio', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('imagen_portada', models.URLField(blank=True)),
                ('visto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True)),
                ('anio', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('temporadas', models.IntegerField()),
                ('capitulos', models.IntegerField()),
                ('duracion_capitulo', models.DurationField()),
                ('imagen_portada', models.URLField(blank=True)),
                ('visto', models.BooleanField(default=False)),
            ],
        ),
    ]
