# Generated by Django 5.1.2 on 2024-10-25 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('comentario', models.TextField(blank=True)),
                ('anio', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('imagen_portada', models.URLField(blank=True)),
                ('visto', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('comentario', models.TextField(blank=True)),
                ('anio', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('temporadas', models.IntegerField()),
                ('capitulos', models.IntegerField()),
                ('duracion_capitulo', models.DurationField()),
                ('imagen_portada', models.URLField(blank=True)),
                ('visto', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Peliculas',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
