# Generated by Django 5.1.2 on 2024-10-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_alter_pelicula_director_alter_serie_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='visto',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='visto',
        ),
    ]
