# Generated by Django 5.1.2 on 2024-10-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_contenidousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='trailer',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='trailer',
            field=models.URLField(blank=True),
        ),
    ]
